### ISSUE TITLE
Two tasks created - one fails, another doesnt ?

### ISSUE THREAD

**Issue by trainoasis** [kentaro-m/task-completed-checker-action#42]
I see there's two tasks created for some reason and they are not synced (one fails, one does not), wanted to make sure what I'm doing wrong? 

![Screen Shot 2022-10-28 at 12 59 32](https://user-images.githubusercontent.com/6115601/198571858-b76231de-80d8-42af-b72b-382d53dd1721.png)

The only thing I added was a new workflow, but adjusted when the workflow is called, likely that's the issue:

```
name: "PR Tasks Completed Check"
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  task-check:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/task-completed-checker-action@v0.1.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

Are there too many `types` defined or something? I wanna make sure this task checker runs on every push/merge & also when a PR is opened, description edited etc. 

Any help appreciated.
