### ISSUE TITLE
Task Completed Checker job is not getting attached to it's host job

### ISSUE THREAD

**Issue by MalcolmShelley** [kentaro-m/task-completed-checker-action#87]
When running multiple jobs in parallel, the Task Completed Checker job is not getting attached to the job/step running the action.

Configuration for `kentaro-m/task-completed-checker-action@v0.1.2` follows
```
name: "PR Submission Checks"
on:
  pull_request_review:
    types: [submitted]

# This workflow checks that the PR has a checklist of tasks completed
jobs:
  task-completion-check:
    name: Task Completion Check
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-22.04

    permissions:
      contents: read
      pull-requests: write
      checks: write

    steps:
      - uses: kentaro-m/task-completed-checker-action@v0.1.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
```

![Image](https://github.com/user-attachments/assets/6e8b01db-e30f-4173-922f-ee0e771c4bf9)
